In [5]:
# Load datasetnya menggunakan pandas    

import pandas as pd
import numpy as np

df = pd.read_csv('../datasets/foodpanda_analysis_dataset.csv', encoding='utf-8')  

df.head()

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,C5663,Male,Adult,Peshawar,1/14/2024,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,3,10/14/2024,Cancelled
1,C2831,Male,Adult,Multan,7/7/2024,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2,8/21/2025,Delayed
2,C2851,Other,Senior,Multan,6/20/2025,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3,9/19/2024,Delayed
3,C1694,Female,Senior,Peshawar,9/5/2023,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2,6/29/2025,Delayed
4,C4339,Other,Senior,Lahore,12/29/2023,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,3,3/6/2025,Cancelled

In [6]:
# Menampilkan 5 baris pertama dari dataset

df.head()

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,C5663,Male,Adult,Peshawar,1/14/2024,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,3,10/14/2024,Cancelled
1,C2831,Male,Adult,Multan,7/7/2024,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2,8/21/2025,Delayed
2,C2851,Other,Senior,Multan,6/20/2025,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3,9/19/2024,Delayed
3,C1694,Female,Senior,Peshawar,9/5/2023,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2,6/29/2025,Delayed
4,C4339,Other,Senior,Lahore,12/29/2023,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,3,3/6/2025,Cancelled

In [7]:
# Mengecek informasi dataset dan tipe data setiap kolom

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      6000 non-null   str
 1   gender           6000 non-null   str
 2   age              6000 non-null   str
 3   city             6000 non-null   str
 4   signup_date      6000 non-null   str
 5   order_id         6000 non-null   str
 6   order_date       6000 non-null   str
 7   restaurant_name  6000 non-null   str
 8   dish_name        6000 non-null   str
 9   category         6000 non-null   str
 10  quantity         6000 non-null   int64
 11  price            6000 non-null   float64
 12  payment_method   6000 non-null   str
 13  order_frequency  6000 non-null   int64
 14  last_order_date  6000 non-null   str
 15  loyalty_points   6000 non-null   int64
 16  churned          6000 non-null   str
 17  rating           6000 non-null   int64
 18  rating_date      6000 non-null   str
 19  delivery_status  6000 non-null   str
dtypes: float64(1), int64(4), str(15)
memory usage: 937.6 KB

In [8]:
# Mengecek jumlah nilai yang hilang (missing values) di setiap kolom

df.isnull().sum()

customer_id        0
gender             0
age                0
city               0
signup_date        0
order_id           0
order_date         0
restaurant_name    0
dish_name          0
category           0
quantity           0
price              0
payment_method     0
order_frequency    0
last_order_date    0
loyalty_points     0
churned            0
rating             0
rating_date        0
delivery_status    0
dtype: int64

In [9]:
# 

df.describe(include='all')

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
count,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000.000000,6000.000000,6000,6000.000000,6000,6000.000000,6000,6000.000000,6000,6000
unique,6000,3,3,5,730,6000,730,5,5,5,NaN,NaN,3,NaN,366,NaN,2,NaN,366,3
top,C5663,Female,Teenager,Multan,10/18/2023,O9663,9/8/2024,Subway,Pasta,Italian,NaN,NaN,Cash,NaN,2/6/2025,NaN,Active,NaN,4/19/2025,Delivered
freq,1,2018,2062,1256,18,1,20,1260,1262,1236,NaN,NaN,2039,NaN,28,NaN,3016,NaN,27,2060
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.991667,800.524880,NaN,25.304667,NaN,250.173667,NaN,2.996833,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.414778,404.855029,NaN,14.358930,NaN,144.608478,NaN,1.406113,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,100.300000,NaN,1.000000,NaN,0.000000,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,441.997500,NaN,13.000000,NaN,125.000000,NaN,2.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,806.460000,NaN,25.000000,NaN,249.500000,NaN,3.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,1149.737500,NaN,37.000000,NaN,378.000000,NaN,4.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,1499.950000,NaN,50.000000,NaN,500.000000,NaN,5.000000,NaN,NaN

In [10]:
df.columns

Index(['customer_id', 'gender', 'age', 'city', 'signup_date', 'order_id',
       'order_date', 'restaurant_name', 'dish_name', 'category', 'quantity',
       'price', 'payment_method', 'order_frequency', 'last_order_date',
       'loyalty_points', 'churned', 'rating', 'rating_date',
       'delivery_status'],
      dtype='str')

In [11]:
df.dtypes

customer_id            str
gender                 str
age                    str
city                   str
signup_date            str
order_id               str
order_date             str
restaurant_name        str
dish_name              str
category               str
quantity             int64
price              float64
payment_method         str
order_frequency      int64
last_order_date        str
loyalty_points       int64
churned                str
rating               int64
rating_date            str
delivery_status        str
dtype: object

In [12]:
df['signup_date'] = pd.to_datetime(df['signup_date'], format='%m/%d/%Y')
df['order_date'] = pd.to_datetime(df['order_date'], format='%m/%d/%Y')
df['rating_date'] = pd.to_datetime(df['rating_date'], format='%m/%d/%Y')
df.dtypes

customer_id                   str
gender                        str
age                           str
city                          str
signup_date        datetime64[us]
order_id                      str
order_date         datetime64[us]
restaurant_name               str
dish_name                     str
category                      str
quantity                    int64
price                     float64
payment_method                str
order_frequency             int64
last_order_date               str
loyalty_points              int64
churned                       str
rating                      int64
rating_date        datetime64[us]
delivery_status               str
dtype: object

In [13]:
df['last_order_date'] = pd.to_datetime(df['last_order_date'], format='%m/%d/%Y')

In [14]:
df.head(60)

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,C5663,Male,Adult,Peshawar,2024-01-14,O9663,2023-08-23,McDonald's,Burger,Italian,5,1478.27,Cash,38,2025-07-19,238,Active,3,2024-10-14,Cancelled
1,C2831,Male,Adult,Multan,2024-07-07,O6831,2023-08-23,KFC,Burger,Italian,3,956.04,Wallet,24,2024-11-25,81,Active,2,2025-08-21,Delayed
2,C2851,Other,Senior,Multan,2025-06-20,O6851,2023-08-23,Pizza Hut,Fries,Italian,2,882.51,Cash,42,2025-05-10,82,Inactive,3,2024-09-19,Delayed
3,C1694,Female,Senior,Peshawar,2023-09-05,O5694,2023-08-23,Subway,Pizza,Dessert,4,231.30,Card,27,2025-07-24,45,Inactive,2,2025-06-29,Delayed
4,C4339,Other,Senior,Lahore,2023-12-29,O8339,2023-08-24,KFC,Sandwich,Dessert,1,1156.69,Cash,35,2024-12-21,418,Inactive,3,2025-03-06,Cancelled
5,C6543,Other,Adult,Karachi,2023-09-28,O10543,2023-08-24,Burger King,Pizza,Fast Food,5,1213.62,Cash,45,2024-10-10,418,Inactive,4,2025-06-01,Delivered
6,C6423,Male,Adult,Lahore,2025-04-08,O10423,2023-08-24,McDonald's,Pasta,Continental,5,672.91,Wallet,31,2025-05-25,347,Active,1,2025-03-04,Cancelled
7,C4621,Male,Adult,Peshawar,2024-02-05,O8621,2023-08-24,Pizza Hut,Pizza,Chinese,2,271.74,Cash,14,2025-05-01,429,Active,2,2024-09-30,Delivered
8,C5146,Other,Senior,Karachi,2024-12-17,O9146,2023-08-24,KFC,Pizza,Dessert,5,596.96,Wallet,1,2025-05-16,24,Active,4,2024-10-27,Delayed
9,C3579,Male,Adult,Karachi,2023-10-13,O7579,2023-08-24,Pizza Hut,Pizza,Continental,2,1443.25,Cash,15,2025-02-23,270,Inactive,3,2024-10-11,Delayed
10,C5535,Male,Adult,Lahore,2025-07-30,O9535,2023-08-24,Subway,Sandwich,Continental,2,645.52,Cash,32,2025-04-08,133,Active,4,2024-12-05,Delayed
11,C3894,Female,Senior,Multan,2025-01-24,O7894,2023-08-24,Burger King,Burger,Fast Food,1,126.53,Wallet,45,2024-09-26,48,Inactive,2,2025-08-20,Cancelled
12,C4071,Male,Senior,Islamabad,2024-12-27,O8071,2023-08-24,Subway,Pizza,Italian,1,465.75,Card,29,2024-12-26,394,Active,4,2025-04-16,Cancelled
13,C4231,Female,Senior,Multan,2025-04-11,O8231,2023-08-24,Burger King,Sandwich,Continental,3,796.91,Wallet,39,2024-11-12,5,Inactive,5,2025-02-27,Delivered
14,C3914,Male,Teenager,Islamabad,2023-11-29,O7914,2023-08-24,KFC,Pizza,Fast Food,4,1140.76,Wallet,23,2025-04-22,492,Inactive,5,2025-04-19,Delayed
15,C5681,Other,Adult,Islamabad,2024-11-25,O9681,2023-08-25,Subway,Pizza,Continental,1,1285.18,Cash,10,2025-04-09,196,Inactive,2,2025-06-10,Delayed
16,C4975,Female,Teenager,Karachi,2025-06-20,O8975,2023-08-25,Burger King,Burger,Dessert,1,673.86,Wallet,38,2025-07-07,439,Inactive,2,2025-07-09,Delivered
17,C2876,Female,Senior,Islamabad,2024-12-30,O6876,2023-08-25,KFC,Burger,Chinese,2,330.93,Cash,45,2025-07-17,455,Active,2,2024-11-28,Cancelled
18,C6144,Other,Teenager,Peshawar,2024-08-05,O10144,2023-08-25,Subway,Pasta,Fast Food,2,991.17,Wallet,6,2025-04-22,101,Active,2,2025-03-27,Cancelled
19,C5092,Female,Adult,Lahore,2023-10-05,O9092,2023-08-25,Subway,Pasta,Chinese,1,1485.16,Card,46,2025-04-24,171,Inactive,3,2025-08-05,Delayed
20,C2747,Female,Adult,Lahore,2024-08-30,O6747,2023-08-25,Subway,Sandwich,Italian,2,802.12,Wallet,22,2024-09-15,32,Inactive,4,2025-06-11,Cancelled
21,C3406,Female,Teenager,Lahore,2024-02-25,O7406,2023-08-25,Pizza Hut,Sandwich,Italian,1,1394.47,Cash,13,2025-06-16,273,Inactive,2,2025-07-20,Delayed
22,C2975,Male,Teenager,Multan,2024-09-28,O6975,2023-08-25,Pizza Hut,Pizza,Italian,3,1287.69,Wallet,49,2025-06-05,35,Active,4,2024-11-10,Delivered
23,C5497,Other,Adult,Lahore,2025-01-26,O9497,2023-08-25,Burger King,Pasta,Continental,5,785.37,Card,49,2024-10-21,463,Active,2,2025-05-19,Delivered
24,C2748,Other,Teenager,Karachi,2024-07-07,O6748,2023-08-25,Pizza Hut,Fries,Dessert,2,1304.80,Cash,2,2024-12-01,435,Inactive,1,2024-11-29,Cancelled
25,C1929,Female,Teenager,Peshawar,2023-11-27,O5929,2023-08-26,KFC,Fries,Continental,1,599.70,Wallet,35,2025-06-26,172,Active,4,2024-11-10,Delayed
26,C5124,Male,Adult,Lahore,2025-05-25,O9124,2023-08-26,McDonald's,Burger,Continental,3,1065.15,Cash,38,2024-12-13,250,Inactive,2,2025-04-18,Cancelled
27,C6250,Male,Teenager,Lahore,2024-06-29,O10250,2023-08-26,McDonald's,Pasta,Chinese,5,576.33,Card,7,2025-05-03,60,Active,3,2025-06-03,Cancelled
28,C1351,Female,Adult,Karachi,2024-06-16,O5351,2023-08-26,KFC,Fries,Chinese,3,761.47,Card,3,2025-01-08,240,Inactive,2,2024-11-29,Delivered
29,C5795,Female,Senior,Islamabad,2023-11-07,O9795,2023-08-26,KFC,Pizza,Italian,5,1267.20,Card,32,2024-11-10,72,Active,5,2024-10-21,Delayed
30,C5513,Male,Teenager,Islamabad,2025-07-20,O9513,2023-08-26,KFC,Pizza,Continental,3,1044.89,Card,31,2024-09-15,496,Inactive,2,2024-12-27,Delayed
31,C6362,Female,Senior,Islamabad,2023-11-22,O10362,2023-08-26,Burger King,Pizza,Chinese,4,343.52,Card,34,2024-09-29,164,Active,3,2025-01-25,Delivered
32,C6340,Male,Senior,Multan,2025-07-07,O10340,2023-08-26,Burger King,Sandwich,Continental,2,209.77,Cash,16,2024-11-20,453,Active,3,2024-09-04,Cancelled
33,C5444,Other,Teenager,Peshawar,2025-07-02,O9444,2023-08-26,Subway,Pasta,Chinese,3,1052.17,Cash,12,2025-04-21,14,Inactive,3,2025-02-08,Delayed
34,C1454,Female,Adult,Islamabad,2025-07-01,O5454,2023-08-26,McDonald's,Pizza,Italian,2,1030.25,Wallet,5,2025-06-26,273,Active,1,2025-02-05,Cancelled
35,C4748,Other,Adult,Peshawar,2024-03-10,O8748,2023-08-26,Subway,Sandwich,Italian,5,909.48,Wallet,3,2025-07-28,224,Inactive,3,2025-05-25,Cancelled
36,C2827,Male,Teenager,Multan,2025-03-05,O6827,2023-08-26,Pizza Hut,Sandwich,Italian,3,192.88,Wallet,26,2025-06-03,18,Active,3,2025-01-13,Cancelled
37,C3338,Female,Senior,Lahore,2023-12-04,O7338,2023-08-26,McDonald's,Burger,Chinese,2,1471.81,Wallet,25,2024-12-27,444,Active,3,2025-06-14,Delivered
38,C1614,Other,Adult,Lahore,2023-12-31,O5614,2023-08-26,Subway,Pizza,Italian,1,956.03,Card,39,2025-04-19,167,Inactive,5,2025-01-04,Delivered
39,C4382,Male,Senior,Multan,2025-01-20,O8382,2023-08-27,Pizza Hut,Pizza,Dessert,3,222.14,Wallet,4,2025-03-25,148,Inactive,2,2025-01-01,Delayed
40,C1827,Other,Adult,Lahore,2024-05-24,O5827,2023-08-27,Burger King,Pasta,Italian,2,522.00,Cash,12,2025-03-30,246,Inactive,3,2024-09-20,Delayed
41,C5009,Male,Teenager,Islamabad,2024-03-25,O9009,2023-08-27,Pizza Hut,Pizza,Italian,3,795.30,Card,15,2025-06-02,179,Inactive,4,2025-01-13,Delayed
42,C3152,Other,Teenager,Multan,2024-02-26,O7152,2023-08-27,Subway,Burger,Chinese,3,768.49,Wallet,40,2024-12-23,495,Inactive,5,2025-01-06,Delivered
43,C4729,Female,Teenager,Multan,2025-07-18,O8729,2023-08-27,KFC,Fries,Chinese,2,198.12,Card,7,2025-01-31,13,Inactive,3,2025-06-27,Cancelled
44,C5046,Other,Teenager,Islamabad,2024-08-15,O9046,2023-08-27,KFC,Fries,Chinese,1,196.28,Card,22,2025-08-17,378,Inactive,4,2025-03-04,Delivered
45,C3588,Other,Teenager,Lahore,2024-01-07,O7588,2023-08-27,Subway,Burger,Continental,1,364.91,Card,1,2025-05-06,98,Active,5,2025-08-18,Delayed
46,C3247,Female,Senior,Multan,2023-11-27,O7247,2023-08-27,McDonald's,Sandwich,Italian,5,275.53,Cash,7,2024-12-06,138,Active,2,2025-06-22,Delivered
47,C2454,Other,Teenager,Karachi,2023-12-04,O6454,2023-08-27,KFC,Pizza,Italian,1,249.90,Cash,20,2025-03-22,70,Inactive,1,2025-07-20,Delayed
48,C4046,Other,Adult,Karachi,2024-11-10,O8046,2023-08-27,Subway,Sandwich,Continental,4,1226.08,Cash,32,2025-02-06,372,Active,4,2025-06-18,Delivered
49,C6194,Female,Adult,Lahore,2023-10-09,O10194,2023-08-28,Subway,Fries,Continental,3,1120.65,Card,46,2024-12-02,453,Active,4,2025-08-19,Cancelled
50,C5845,Other,Senior,Multan,2024-11-07,O9845,2023-08-28,Subway,Sandwich,Fast Food,3,1056.20,Card,26,2024-10-14,116,Active,5,2025-02-16,Cancelled
51,C6804,Female,Adult,Peshawar,2025-01-16,O10804,2023-08-28,Burger King,Burger,Continental,3,931.02,Wallet,30,2025-07-10,211,Inactive,3,2025-03-18,Delayed
52,C1490,Other,Senior,Lahore,2024-12-02,O5490,2023-08-28,Pizza Hut,Pizza,Fast Food,2,1431.45,Wallet,15,2025-05-04,190,Inactive,4,2024-10-08,Cancelled
53,C4203,Male,Adult,Multan,2024-04-17,O8203,2023-08-28,KFC,Pizza,Italian,5,167.62,Card,13,2024-09-08,388,Active,4,2024-11-07,Delivered
54,C6818,Male,Adult,Islamabad,2024-10-22,O10818,2023-08-28,Subway,Pasta,Chinese,2,118.82,Card,12,2025-05-10,87,Active,1,2024-09-14,Cancelled
55,C2583,Female,Adult,Karachi,2024-08-10,O6583,2023-08-29,Pizza Hut,Pasta,Fast Food,1,492.46,Cash,10,2025-01-16,383,Active,1,2024-09-09,Delivered
56,C1891,Male,Teenager,Multan,2023-11-28,O5891,2023-08-29,Pizza Hut,Pasta,Chinese,5,1275.96,Card,28,2024-11-09,312,Inactive,2,2024-12-29,Delivered
57,C1972,Male,Teenager,Multan,2024-06-03,O5972,2023-08-29,McDonald's,Sandwich,Chinese,1,1462.99,Wallet,36,2025-03-26,316,Inactive,4,2024-11-30,Cancelled
58,C5895,Female,Adult,Karachi,2025-02-19,O9895,2023-08-29,McDonald's,Pasta,Chinese,2,1221.24,Cash,13,2025-02-12,286,Active,4,2025-03-15,Cancelled
59,C5179,Male,Adult,Multan,2023-09-03,O9179,2023-08-29,McDonald's,Pasta,Fast Food,1,1033.71,Card,47,2024-08-30,4,Active,2,2024-12-24,Delivered

In [15]:
labels = ['New Customer', 'Occasional', 'Regular', 'Loyal', 'VIP']

df['loyalty_group'] = pd.cut(
    df['loyalty_points'],
    bins=[0,100,200,300,400,500],
    labels=labels
)

In [16]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="postgres",
    user="postgres",
    password="admin12345",
    port="5432"
)

print("Berhasil connect")

Berhasil connect

In [17]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:admin12345@localhost:5432/postgres"
)

try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT 1"))
        print("Koneksi berhasil, SELECT 1 =", result.scalar())
except Exception as e:
    print("Koneksi gagal:", e)

Koneksi berhasil, SELECT 1 = 1

In [18]:
df.to_sql(
    "customer_behavior_foodpanda",
    engine,
    if_exists="replace",
    index=False, 
    schema="project_data_analisis"
)

1000